language: node_js

env:
  global:
    - GH_REF: github.com/huangxiaochang/ui-components.git

install:
  - yarn bootstrap

cache:
  directories:
    - node_modules

git:
  depth: 1

node_js:
  - "12.21.0"

# only master branches 
branches:
  only:
    - master

script:
  - yarn lint
  - yarn test    
  - yarn fast-build
  - yarn website-github-page

# release to github
after_script:
  - sh scripts/release-ci.sh
  

# deploy to github page 
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $ui_component_token
  local-dir: website-dist
  target-branch: website-pages
  verbose: true
  on:
    branch: master

# deploy to npm
# deploy:
#   provider: npm
#   email: $NPM_EMAIL
#   api_key: $NPM_ACCESS_TOKEN
#   on:
#     branch: master
#     tags: ture

