language: node_js

install:
  - yarn bootstrap

cache:
  directories:
    - node_modules

git:
  depth: 1

node_js:
  - "12.21.0"

# only master branches 
branches:
  only:
    - master

script:
  - yarn lint
  - yarn test    
  - yarn build
  - yarn website-github-page

# deploy to github page 
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $ui_component_token
  local-dir: website-dist
  target-branch: website-pages
  verbose: true
  on:
    branch: master

env:
  global:
    - GH_REF: https://github.com/huangxiaochang/ui-components.git
    # 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
